### PR TITLE
Add Neon Devnet Support

### PR DESCRIPTION
**Pull request by Sj-001**
RPC: https://devnet.neonevm.org
@Uxio0

### CODE REVIEW

**Comment by Sj-001** [comment]
@mmv08 Please check:)

**Comment by mmv08** [comment]
Please try to replay the transaction to get the same address.

**Comment by Sj-001** [comment]
> Please try to replay the transaction to get the same address.

@mmv08 I cannot replay transaction on Neon Devnet. Can you please deploy on your end? You can grab some test airdrops from here : https://neonfaucet.org/

**Comment by mmv08** [comment]
> > Please try to replay the transaction to get the same address.
> 
> @mmv08 I cannot replay transaction on Neon Devnet. Can you please deploy on your end? You can grab some test airdrops from here : https://neonfaucet.org/

I'm sorry, but I have lots of work to do. Could you please clarify why you cannot replay a transaction?

**Pull request closed without merging**
